project:
  type: website

website:
  title: "Monash NUMBATs"
  navbar:
    left:
      - href: people/index.qmd
        text: People
      - events.qmd
      - href: courses.qmd
        text: Courses
      - contact.qmd
      - href: posts/index.qmd
        text: Posts


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
